### PR TITLE
fixed deprecated "environments" module in examples, closes #694

### LINKED ISSUE #694: ModuleNotFoundError: No module named 'erdpy.environments'
hey, I'm new to elrond network and trying to setup workspace by docs. However, for some reason can't use python bindings to test adder example with `playground.py`. I managed to interact with the contract using bash script, but not python
```
[/mnt/tmpfs/elrond-playground]$ python3 ./adder/interaction/playground.py 
Traceback (most recent call last):
  File "./adder/interaction/playground.py", line 8, in <module>
    from erdpy.environments import TestnetEnvironment
ModuleNotFoundError: No module named 'erdpy.environments'

$ tree -L 1 /mnt/tmpfs/elrond-playground
/mnt/tmpfs/elrond-playground
├── adder
├── elrond.workspace.json
└── erdjs-snippets

2 directories, 1 file
```

### PR DESCRIPTION
**Pull request by buff3r0verfl0w**
looks like I fixed it for this example, but you're feel free to review/edit repo

### CODE REVIEW

**Comment by buff3r0verfl0w** [comment]
tests:
```
[/mnt/tmpfs/elrond-playground/adder]$ python3 interaction/playground.py --pem ~/Документы/elrond-smart-contracts/adder/wallets/users/alice.pem
INFO:accounts:Account.sync_nonce()
INFO:accounts:Account.sync_nonce() done: 22
Let's run a flow.
1. Deploy
2. Query getSum()
3. Add()
Choose:
1
INFO:proxy:Transaction not yet done.
INFO:proxy:Transaction not yet done.
INFO:proxy:Transaction not yet done.
INFO:proxy:Transaction not yet done.
INFO:examples:Tx hash: 7c3cd6d5c0ad12a9c777896806470ee06d95e0a3bf495700d6e890eadc599c52
INFO:examples:Contract address: erd1qqqqqqqqqqqqqpgq6h28ftwk3ny2uxw8n7q6a00r0cuxldng6wvshg9jvk
Let's run a flow.
1. Deploy
2. Query getSum()
3. Add()
Choose:
2
INFO:examples:Answer: [{'base64': 'ZA==', 'hex': '64', 'number': 100}]
Let's run a flow.
1. Deploy
2. Query getSum()
3. Add()
Choose:
3
Enter number:1
INFO:transactions:Transaction.send: nonce=23
INFO:transactions:Hash: 42852ff11788a5443b5ae5e61694afb58e7e4319ebc2650d36a38df2b76249f2
INFO:utils:View this transaction in the Elrond Testnet Explorer: https://testnet-explorer.elrond.com/transactions/42852ff11788a5443b5ae5e61694afb58e7e4319ebc2650d36a38df2b76249f2
INFO:examples:Tx hash: 42852ff11788a5443b5ae5e61694afb58e7e4319ebc2650d36a38df2b76249f2
Let's run a flow.
1. Deploy
2. Query getSum()
3. Add()
Choose:
2
INFO:examples:Answer: [{'base64': 'ZQ==', 'hex': '65', 'number': 101}]
```

**Comment by buff3r0verfl0w** [comment]
hey, @andrei-marinica! Are you able to review this?

**Review by claudiu725 — APPROVED** [review]

**Comment by andreibancioiu** [comment]
@buff3r0verfl0w, thank you for the contribution :pray: :tada: 

I leave this link here, for future reference:

https://github.com/ElrondNetwork/elrond-sdk-erdpy/blob/main/examples/contracts.py

**Review by andreibancioiu — APPROVED** [review]

**Comment by buff3r0verfl0w** [comment]
@andreibancioiu I was also confused by not working faucet in official guide, first time I spent maybe 3h to just create wallet end setup erdpy...

**Pull request merged**
